export const saturdayLessons = [
  {
    id: "cheatsheet",
    title: "Python Basics Cheatsheet",
    emoji: "🐍",
    description: "Quick reference guide for all Python basics — variables, loops, functions, dictionaries, and more.",
    tags: ["Reference", "Beginner"],
    color: "indigo",
  },
  {
    id: "review",
    title: "Review Exercises",
    emoji: "🎮",
    description: "8 hands-on exercises covering character stats, math, input, conditionals, loops, lists, and functions.",
    tags: ["Exercises", "Review"],
    color: "emerald",
  },
  {
    id: "review2",
    title: "Review Exercises Part 2",
    emoji: "🎮",
    description: "More practice with conditionals, lists, loops, functions, and a bonus battle challenge.",
    tags: ["Exercises", "Review"],
    color: "teal",
  },
];

export const dictionaryExercises = [
  {
    id: "dict-ex0",
    title: "Dictionary Basics",
    emoji: "📚",
    description: "Game characters, pet stats, high scores, and a mini item shop project.",
    tags: ["Dictionaries", "Beginner"],
    color: "amber",
  },
  {
    id: "dict-ex1",
    title: "Roblox Catalog Shop",
    emoji: "🎮",
    description: "Create a catalog with Roblox items and prices, update and display them.",
    tags: ["Dictionaries", "Roblox"],
    color: "rose",
  },
  {
    id: "dict-ex2",
    title: "Robux Balance",
    emoji: "💰",
    description: "Use input, type conversion, and conditionals to check if you can afford items.",
    tags: ["Dictionaries", "Input"],
    color: "orange",
  },
  {
    id: "dict-ex3",
    title: "Buying Items",
    emoji: "🛒",
    description: "Build a buying system with inventory management and Robux tracking.",
    tags: ["Dictionaries", "Conditionals"],
    color: "sky",
  },
  {
    id: "dict-ex4",
    title: "Selling Items Back",
    emoji: "💸",
    description: "Add selling functionality with 50% resale value and inventory management.",
    tags: ["Dictionaries", "Conditionals"],
    color: "lime",
  },
  {
    id: "dict-project-a",
    title: "Project: Ultimate Roblox Shop",
    emoji: "🏪",
    description: "Build a complete shop with buying, selling, and stats tracking in a game loop.",
    tags: ["Project", "Dictionaries"],
    color: "fuchsia",
  },
  {
    id: "dict-project-b",
    title: "Project: Guess Who — Roblox Edition",
    emoji: "🎲",
    description: "Build a text-based Guess Who game using dictionaries and random selection.",
    tags: ["Project", "Game"],
    color: "cyan",
  },
];

export const sundayLessons = [
  {
    id: "algorithms",
    title: "Algorithms — CCC Prep",
    emoji: "🏆",
    description: "Algorithmic thinking for competitive programming — scanning, accumulation, two-pointer patterns.",
    tags: ["Algorithms", "CCC"],
    color: "blue",
  },
  {
    id: "dfs-bfs",
    title: "DFS & BFS — Grid Traversal",
    emoji: "🗺️",
    description: "2D arrays, grid traversal, and building toward CCC Question 5 problems.",
    tags: ["Algorithms", "Grids"],
    color: "purple",
  },
  {
    id: "graphs",
    title: "DFS Practice — Graph Exploration",
    emoji: "🌐",
    description: "Depth-First Search on grids — flood fill, island counting, and maze solving.",
    tags: ["DFS", "Recursion"],
    color: "red",
  },
];

export const heapExercises = [
  {
    id: "heap-intro",
    title: "Heap Intro & Concepts",
    emoji: "🏔️",
    description: "What heaps are, how they're stored, bubble up/down, Python's heapq module, and max-heap trick.",
    tags: ["Heaps", "Reference"],
    color: "amber",
  },
  {
    id: "heap-ex1",
    title: "Find the 3rd Largest",
    emoji: "🥉",
    description: "Use heapq to find the 3rd largest element in a list.",
    tags: ["Heaps", "Exercises"],
    color: "orange",
  },
  {
    id: "heap-ex2",
    title: "K Smallest Elements",
    emoji: "🔢",
    description: "Return the k smallest elements from a list using a heap.",
    tags: ["Heaps", "Exercises"],
    color: "emerald",
  },
  {
    id: "heap-ex3",
    title: "Sort Using a Heap",
    emoji: "📊",
    description: "Sort a list using only heap operations — no built-in sort!",
    tags: ["Heaps", "Exercises"],
    color: "indigo",
  },
  {
    id: "heap-ex4",
    title: "Task Scheduler",
    emoji: "⏰",
    description: "Process tasks in priority order using a heap-based scheduler.",
    tags: ["Heaps", "Exercises"],
    color: "violet",
  },
  {
    id: "heap-tips",
    title: "Heap Tips & Reference",
    emoji: "💡",
    description: "Time complexities, when to use heaps, common mistakes, and debug checklist.",
    tags: ["Heaps", "Reference"],
    color: "blue",
  },
];

export const heap2Exercises = [
  {
    id: "heap2-ex1",
    title: "Top K Frequent Elements",
    emoji: "📊",
    description: "Find the k most frequent elements using a min-heap of size k.",
    tags: ["Heaps", "Exercises"],
    color: "amber",
  },
  {
    id: "heap2-ex2",
    title: "CCC — Bronze Count",
    emoji: "🥉",
    description: "CCC J3: Find the 3rd highest score and count how many participants achieved it.",
    tags: ["Heaps", "CCC"],
    color: "sky",
  },
  {
    id: "heap2-ex3",
    title: "Build a Heap from Scratch",
    emoji: "🔨",
    description: "Implement bubble up, bubble down, and heapify — no heapq allowed!",
    tags: ["Heaps", "Exercises"],
    color: "violet",
  },
];

export const sundayAnswers = [
  {
    id: "algorithms-answers",
    title: "Algorithms — Answer Key",
    emoji: "🔑",
    description: "Complete solutions with explanations for all algorithm exercises.",
    tags: ["Answers", "Algorithms"],
    color: "green",
  },
  {
    id: "dfs-bfs-answers",
    title: "DFS & BFS — Answer Key",
    emoji: "🔑",
    description: "Complete solutions for grid traversal and DFS/BFS exercises.",
    tags: ["Answers", "Grids"],
    color: "green",
  },
];

export const functionExercises = [
  {
    id: "func-intro",
    title: "Functions — What & Why",
    emoji: "📖",
    description: "What functions are, return vs print, and how to call them.",
    tags: ["Functions", "Reference"],
    color: "violet",
  },
  {
    id: "func-ex1",
    title: "XP Calculator",
    emoji: "⭐",
    description: "Calculate experience points needed to level up.",
    tags: ["Functions", "Easy"],
    color: "amber",
  },
  {
    id: "func-ex2",
    title: "Health System",
    emoji: "❤️",
    description: "Manage player health with healing, damage, and capping.",
    tags: ["Functions", "Easy"],
    color: "rose",
  },
  {
    id: "func-ex3",
    title: "Item Counter",
    emoji: "🎒",
    description: "Count items in an inventory list, case-insensitive.",
    tags: ["Functions", "Medium"],
    color: "emerald",
  },
  {
    id: "func-ex4",
    title: "Shop Calculator",
    emoji: "🛒",
    description: "Calculate shop totals with a bulk discount.",
    tags: ["Functions", "Medium"],
    color: "orange",
  },
  {
    id: "func-tips",
    title: "Tips & Common Mistakes",
    emoji: "💡",
    description: "Common mistakes, print vs return, and how to read error messages.",
    tags: ["Functions", "Reference"],
    color: "blue",
  },
];

export const discordBotExercises = [
  {
    id: "func-discord1",
    title: "Greeting Bot",
    emoji: "👋",
    description: "Write greeting and farewell functions that your bot sends to Discord.",
    tags: ["Discord", "Functions", "Easy"],
    color: "indigo",
    isDiscord: true,
  },
  {
    id: "func-discord2",
    title: "Dice Roller Bot",
    emoji: "🎲",
    description: "Build a dice roller with random, loops, and helper functions.",
    tags: ["Discord", "Functions", "Medium"],
    color: "violet",
    isDiscord: true,
  },
  {
    id: "func-discord3",
    title: "Poll Bot",
    emoji: "📊",
    description: "Create formatted polls using lists, loops, and enumerate.",
    tags: ["Discord", "Functions", "Medium"],
    color: "fuchsia",
    isDiscord: true,
  },
  {
    id: "func-discord4",
    title: "RPG Profile Card",
    emoji: "🏰",
    description: "Build a full profile card with 4 functions working together.",
    tags: ["Discord", "Functions", "Hard"],
    color: "rose",
    isDiscord: true,
  },
];

export const loopExercises = [
  {
    id: "loop-intro",
    title: "Loops — How They Work",
    emoji: "📖",
    description: "for loops, while loops, range(), break, continue, and the accumulator pattern.",
    tags: ["Loops", "Reference"],
    color: "emerald",
  },
  {
    id: "loop-ex1",
    title: "Countdown Timer",
    emoji: "🚀",
    description: "Build a rocket launch countdown with range() going backwards.",
    tags: ["Loops", "Easy"],
    color: "amber",
  },
  {
    id: "loop-ex2",
    title: "XP Grinder",
    emoji: "⚔️",
    description: "Use a while loop to grind XP until you level up.",
    tags: ["Loops", "Medium"],
    color: "violet",
  },
  {
    id: "loop-ex3",
    title: "Inventory Lister",
    emoji: "🎒",
    description: "Loop through a list and print each item with its number.",
    tags: ["Loops", "Easy"],
    color: "sky",
  },
  {
    id: "loop-ex4",
    title: "Health Regen",
    emoji: "💚",
    description: "Heal your character with a while loop until full HP.",
    tags: ["Loops", "Medium"],
    color: "rose",
  },
  {
    id: "loop-tips",
    title: "Tips & Common Mistakes",
    emoji: "💡",
    description: "Off-by-one errors, infinite loops, accumulator pattern, and debugging.",
    tags: ["Loops", "Reference"],
    color: "blue",
  },
];

export const loopPart2Exercises = [
  {
    id: "loop2-intro",
    title: "break & continue — How They Work",
    emoji: "📖",
    description: "Exit loops early with break, skip iterations with continue, and the while True pattern.",
    tags: ["Loops", "Reference"],
    color: "teal",
  },
  {
    id: "loop2-ex1",
    title: "Find the Exit",
    emoji: "🚪",
    description: "Explore a dungeon and break out when you find the exit.",
    tags: ["Loops", "Medium"],
    color: "amber",
  },
  {
    id: "loop2-ex2",
    title: "Dodge the Obstacles",
    emoji: "⚡",
    description: "Use continue to skip spikes and collect items on a path.",
    tags: ["Loops", "Medium"],
    color: "rose",
  },
  {
    id: "loop2-ex3",
    title: "Loot Filter",
    emoji: "💎",
    description: "Skip cheap loot with continue and stop when your bag is full with break.",
    tags: ["Loops", "Hard"],
    color: "violet",
  },
  {
    id: "loop2-ex4",
    title: "Boss Battle",
    emoji: "🐉",
    description: "Fight a boss using while True, continue for shields, and break for the kill.",
    tags: ["Loops", "Hard"],
    color: "red",
  },
  {
    id: "loop2-tips",
    title: "Tips & Common Mistakes",
    emoji: "💡",
    description: "Unreachable code, missing updates, infinite loops, and break vs continue.",
    tags: ["Loops", "Reference"],
    color: "blue",
  },
];

export const nestedLoopExercises = [
  {
    id: "nloop-intro",
    title: "Nested Loops — How They Work",
    emoji: "📖",
    description: "Grids, triangles, multiplication tables, break behavior, and counting iterations.",
    tags: ["Loops", "Reference"],
    color: "sky",
  },
  {
    id: "nloop-ex1",
    title: "Number Grid",
    emoji: "🔢",
    description: "Print a repeating number grid using nested loops.",
    tags: ["Loops", "Easy"],
    color: "amber",
  },
  {
    id: "nloop-ex2",
    title: "Times Table",
    emoji: "✖️",
    description: "Print the full times table for any number.",
    tags: ["Loops", "Easy"],
    color: "emerald",
  },
  {
    id: "nloop-ex3",
    title: "Coordinate Pairs",
    emoji: "📍",
    description: "Print all (row, col) pairs for a grid.",
    tags: ["Loops", "Medium"],
    color: "indigo",
  },
  {
    id: "nloop-ex4",
    title: "Matching Pairs",
    emoji: "🤝",
    description: "Find all unique pairs from a list of items.",
    tags: ["Loops", "Medium"],
    color: "rose",
  },
  {
    id: "nloop-tips",
    title: "Tips & Common Mistakes",
    emoji: "💡",
    description: "Variable names, break behavior, off-by-one errors, and debugging.",
    tags: ["Loops", "Reference"],
    color: "blue",
  },
];

export const nestedListExercises = [
  {
    id: "nlist-intro",
    title: "Nested Lists — How They Work",
    emoji: "📖",
    description: "2D grids, accessing elements, looping, searching, and tic-tac-toe.",
    tags: ["Lists", "Reference"],
    color: "rose",
  },
  {
    id: "nlist-ex1",
    title: "Sum Each Row",
    emoji: "➕",
    description: "Calculate and print the sum of each row in a grid.",
    tags: ["Lists", "Easy"],
    color: "amber",
  },
  {
    id: "nlist-ex2",
    title: "Find the Largest",
    emoji: "🏆",
    description: "Find the largest number in a 2D grid.",
    tags: ["Lists", "Easy"],
    color: "emerald",
  },
  {
    id: "nlist-ex3",
    title: "Count a Value",
    emoji: "🔍",
    description: "Count how many times a value appears in a grid.",
    tags: ["Lists", "Medium"],
    color: "indigo",
  },
  {
    id: "nlist-ex4",
    title: "Checkerboard",
    emoji: "♟️",
    description: "Create and print a checkerboard pattern.",
    tags: ["Lists", "Medium"],
    color: "violet",
  },
  {
    id: "nlist-tips",
    title: "Tips & Common Mistakes",
    emoji: "💡",
    description: "Index order, grid creation traps, resetting variables, and debugging.",
    tags: ["Lists", "Reference"],
    color: "blue",
  },
];

export const milestones = [
  {
    number: 1,
    title: "Python Fundamentals",
    status: "complete",
    lessons: 6,
    topics: [
      "Variables and data types",
      "Type casting",
      "Operators",
      "User input",
      "Strings (f-strings, slicing, methods)",
      "Lists (append, remove, indexing)",
      "Conditionals (if/elif/else)",
      "While loops",
      "For loops",
      "Functions (basics)",
    ],
  },
  {
    number: 2,
    title: "Intermediate Python",
    status: "active",
    lessons: 5,
    topics: [
      "Dictionaries",
      "List comprehensions",
      "String formatting",
      "Error handling",
      "File I/O",
      "Modules",
    ],
  },
  {
    number: 3,
    title: "Game Development",
    status: "upcoming",
    lessons: 7,
    topics: [
      "Classes & Objects",
      "Inheritance",
      "Game loops",
      "Random module",
      "Time module",
      "Simple graphics",
    ],
  },
  {
    number: 4,
    title: "Real-World Applications",
    status: "upcoming",
    lessons: 5,
    topics: [
      "APIs",
      "Web scraping",
      "Data analysis",
      "Discord bots",
      "Automation",
    ],
  },
  {
    number: 5,
    title: "Advanced Projects",
    status: "upcoming",
    lessons: 9,
    topics: [
      "GUI applications",
      "Databases",
      "Algorithms",
      "Data structures",
      "Final project",
    ],
  },
];

export function getLessonById(id) {
  const all = [
    ...saturdayLessons,
    ...dictionaryExercises,
    ...sundayLessons,
    ...heapExercises,
    ...heap2Exercises,
    ...sundayAnswers,
    ...functionExercises,
    ...discordBotExercises,
    ...loopExercises,
    ...loopPart2Exercises,
    ...nestedLoopExercises,
    ...nestedListExercises,
  ];
  return all.find((l) => l.id === id) || null;
}

export function getAllLessons() {
  return [
    ...saturdayLessons,
    ...dictionaryExercises,
    ...sundayLessons,
    ...heapExercises,
    ...heap2Exercises,
    ...sundayAnswers,
    ...functionExercises,
    ...discordBotExercises,
    ...loopExercises,
    ...loopPart2Exercises,
    ...nestedLoopExercises,
    ...nestedListExercises,
  ];
}
